### ISSUE TITLE
アプリ名の統一

### ISSUE THREAD

**Issue by SatooRu65536** [SatooRu65536/bottle-mails-app#1]
bottle male か bottle message

**Comment by wappon28dev** [comment]
mails (郵便) じゃなくて males (男) で良いんですかね...？

あと, `applicationId` が `com.example` になったままですよ（小声）

https://github.com/SatooRu65536/BottleMales-App/blob/c9267a3a7eafc2220e51687f825ae2d938aa6aba/android/app/build.gradle#L46-L47

**Comment by SatooRu65536** [comment]
malesはやべぇ...
ありがとう
